import { defineStore } from "pinia";
import { ref } from "vue";

export const useListStore = defineStore("list", () => {
const civilStatuses = [
  { label: "Single", value: "Single" },
  { label: "Married", value: "Married" },
  { label: "Widowed", value: "Widowed" },
  { label: "Separated", value: "Separated" },
  { label: "Divorced", value: "Divorced" },
  { label: "Annulled", value: "Annulled" },
];
const religions = [
  { label: "Roman Catholic", value: "Roman Catholic" },
  { label: "Iglesia ni Cristo", value: "Iglesia ni Cristo" },
  { label: "Islam", value: "Islam" },
  { label: "Evangelical", value: "Evangelical" },
  { label: "Born Again Christian", value: "Born Again Christian" },
  { label: "Baptist", value: "Baptist" },
  { label: "Seventh-day Adventist", value: "Seventh-day Adventist" },
  { label: "Jehovah’s Witnesses", value: "Jehovah’s Witnesses" },
  { label: "Church of Christ", value: "Church of Christ" },
  { label: "United Methodist", value: "United Methodist" },
  { label: "Aglipayan", value: "Aglipayan" },
  { label: "Iglesia Filipina Independiente", value: "Iglesia Filipina Independiente" },
  { label: "The Church of Jesus Christ of Latter-day Saints", value: "The Church of Jesus Christ of Latter-day Saints" },
  { label: "Orthodox Christian", value: "Orthodox Christian" },
  { label: "Protestant", value: "Protestant" },
  { label: "Hinduism", value: "Hinduism" },
  { label: "Buddhism", value: "Buddhism" },
  { label: "Judaism", value: "Judaism" },
  { label: "Sikhism", value: "Sikhism" },
  { label: "Baháʼí Faith", value: "Baháʼí Faith" },
  { label: "Indigenous / Traditional Religion", value: "Indigenous / Traditional Religion" },
  { label: "Other", value: "Other" },
  { label: "No Religion", value: "No Religion" },
  { label: "Unknown", value: "Unknown" },
  { label: "Not Stated", value: "Not Stated" },
];
const administrationRoutes = [
    'Buccal',
    'Gastrostomy',
    'Inhalation',
    'Intradermal',
    'Intramuscular',
    'Intravenous',
    'Jejunostomy',
    'Nasogastric',
    'Nasal',
    'Nebulization',
    'Otic',
    'Ophthalmic',
    'Oral',
    'Rectal',
    'Subcutaneous',
    'Sublingual',
    'Topical',
    'Transdermal',
    'Vaginal',
];

const dosageUnits = [
    'ampule',
    'bottle',
    'capsule',
    'dose',
    'drop',
    'g',
    'IU',
    'kg',
    'L',
    'mEq',
    'mg',
    'mcg',
    'mL',
    'mmol',
    'patch',
    'puff',
    'sachet',
    'spray',
    'suppository',
    'tablet',
    'tube',
    'units',
    'vial',
];

const dosageForms = [
    'Ampule',
    'Capsule',
    'Cream',
    'Drops',
    'Elixir',
    'Emulsion',
    'Gel',
    'Granules',
    'Inhaler',
    'Injection',
    'Liquid',
    'Lozenge',
    'Lotion',
    'Nebulization',
    'Ointment',
    'Patch',
    'Pessary',
    'Powder',
    'Sachet',
    'Solution',
    'Spray',
    'Suppository',
    'Suspension',
    'Syrup',
    'Tablet',
];
const supplyUnits = [
    'Ampule',
    'Bag',
    'Blister',
    'Bottle',
    'Box',
    'Bundle',
    'Can',
    'Capsule',
    'Carton',
    'Case',
    'Container',
    'Dozen',
    'Drum',
    'Dropper',
    'Jar',
    'Kit',
    'Pack',
    'Packet',
    'Pair',
    'Piece',
    'Pouch',
    'Roll',
    'Sachet',
    'Set',
    'Strip',
    'Syringe',
    'Tablet',
    'Tin',
    'Tray',
    'Tube',
    'Vial',
];
return {administrationRoutes, dosageUnits, dosageForms, civilStatuses, religions, supplyUnits}
})